categories = [
     "food general",
    "food style_options",
    "amazon prices",
    "food recommendation",
    "food prices",
    "shipment quality",
    "food quality",
    "amazon availability",
    "shipment delivery",
    "shipment prices",
]
