categories = [
     "hotel design_features",
    "platform general",
    "material quality",
    "rooms general",
    "presentation comprehensiveness",
    "food recommendation",
    "platform service",
    "rooms quality",
    "presentation quality",
    "presentation workload",
    "food_drinks prices",
    "food quality",
    "food_drinks style_options",
    "presentation relatability",
    "facilities comfort",
    "assignments workload",
    "faculty comprehensiveness",
    "grades general",
    "rooms miscellaneous",
    "course comprehensiveness",
    "course value",
    "room_amenities miscellaneous",
    "facilities design_features",
    "hotel miscellaneous",
    "hotel comfort",
    "facilities prices",
    "material quantity",
    "faculty response",
    "hotel prices",
    "faculty value",
    "rooms cleanliness",
    "shipment quality",
    "hotel cleanliness",
    "location general",
    "room_amenities cleanliness",
    "hotel general",
    "course relatability",
    "rooms comfort",
    "food general",
    "service general",
    "hotel quality",
    "facilities quality",
    "assignments relatability",
    "facilities cleanliness",
    "rooms design_features",
    "faculty relatability",
    "rooms prices",
    "amazon availability",
    "shipment prices",
    "facilities general",
    "shipment delivery",
    "assignments comprehensiveness",
    "material workload",
    "room_amenities quality",
    "material relatability",
    "course workload",
    "food_drinks quality",
    "food_drinks miscellaneous",
    "course general",
    "room_amenities prices",
    "food style_options",
    "amazon prices",
    "assignments quality",
    "platform prices",
    "course quality",
    "room_amenities general",
    "room_amenities comfort",
    "room_amenities design_features",
    "food prices",
    "faculty general",
    "facilities miscellaneous",
    "material comprehensiveness",
    "assignments quantity",
    "presentation quantity",
]
