categories = [
     "display design_features",
    "ports operation_performance",
    "battery design_features",
    "hard_disc usability",
    "support design_features",
    "ports general",
    "power_supply connectivity",
    "hard_disc quality",
    "memory usability",
    "out_of_scope operation_performance",
    "software price",
    "multimedia_devices general",
    "mouse general",
    "keyboard general",
    "laptop quality",
    "display quality",
    "fans&cooling quality",
    "cpu general",
    "warranty general",
    "memory general",
    "company general",
    "out_of_scope usability",
    "display operation_performance",
    "keyboard design_features",
    "ports quality",
    "keyboard operation_performance",
    "power_supply operation_performance",
    "company quality",
    "laptop price",
    "cpu operation_performance",
    "multimedia_devices usability",
    "shipping operation_performance",
    "shipping quality",
    "graphics operation_performance",
    "keyboard quality",
    "os general",
    "motherboard operation_performance",
    "display price",
    "laptop general",
    "out_of_scope general",
    "cpu quality",
    "battery general",
    "multimedia_devices operation_performance",
    "battery quality",
    "keyboard portability",
    "ports connectivity",
    "laptop design_features",
    "keyboard price",
    "hard_disc operation_performance",
    "support operation_performance",
    "os usability",
    "fans&cooling design_features",
    "fans&cooling general",
    "shipping general",
    "memory quality",
    "company design_features",
    "software quality",
    "memory design_features",
    "power_supply design_features",
    "software general",
    "cpu design_features",
    "support general",
    "laptop miscellaneous",
    "graphics usability",
    "laptop connectivity",
    "software portability",
    "ports usability",
    "hard_disc price",
    "display usability",
    "os miscellaneous",
    "memory operation_performance",
    "power_supply general",
    "support price",
    "laptop portability",
    "cpu price",
    "fans&cooling operation_performance",
    "hardware usability",
    "graphics design_features",
    "ports portability",
    "support quality",
    "multimedia_devices quality",
    "optical_drives usability",
    "keyboard usability",
    "optical_drives general",
    "battery operation_performance",
    "power_supply quality",
    "software design_features",
    "display general",
    "company price",
    "hardware quality",
    "motherboard quality",
    "graphics general",
    "laptop operation_performance",
    "software operation_performance",
    "laptop usability",
    "company operation_performance",
    "optical_drives design_features",
    "warranty quality",
    "os operation_performance",
    "multimedia_devices price",
    "hard_disc design_features",
    "hardware design_features",
    "multimedia_devices connectivity",
    "software usability",
    "hard_disc general",
    "optical_drives operation_performance",
    "hardware operation_performance",
    "shipping price",
    "multimedia_devices design_features",
    "os design_features",
    "ports design_features",
    "hardware price",
    "os quality",
    "hardware general",
]
