categories = [
     "appearance#form",
    "appearance#shoe component",
    "appearance#material",
    "performance#comfort",
    "general",
    "contextofuse#place",
    "contextofuse#purchase\\_context",
    "appearance#general",
    "contextofuse#usage frequency",
    "misc",
    "performance#misc",
    "cost/value",
    "performance#sizing/fit",
    "appearance#color",
    "contextofuse#review\\_temporality",
    "performance#durability",
    "contextofuse#use case",
    "performance#use case applicability",
    "performance#general",
    "performance#support/stability",
    "appearance#misc",
]
